export const UNAUTHORIZED_STATUS_CODE = 403;
export const BAD_REQUEST_STATUS_CODE = 400;
export const SUCCESSFULLY_CREATED_STATUS_CODE = 201;
export const SUCCESSFULLY_FETCHED_STATUS_CODE = 200;
export const SUCCESSFULLY_ACCEPTED_STATUS_CODE = 202;
export const UNAUTHENTICATED_STATUS_CODE = 401;
export const SERVER_ERROR_STATUS_CODE = 500;